# Generated by Django 5.2.12 on 2026-07-03 19:41

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamiento', '0006_servicio_activo_alter_servicio_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('especialidad', models.CharField(blank=True, max_length=100)),
                ('imagen', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='cita',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cita',
            name='operario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='agendamiento.operario'),
        ),
    ]
